### ISSUE TITLE
Enhance Game with Web Interface and UI Improvements

### ISSUE THREAD

**Issue by Vimal-Mudalagi** [kartikeyasaran/guess-the-word#1]
Hi Kartikeya!
I’d love to contribute to this project by creating a **web-based** version of the game. This would include adding a web interface for user interaction, enhancing the **UI,** and using a framework like **Flask** to handle backend functionality. My goal is to make the game more interactive and visually engaging. Please let me know if this aligns with the project's goals or if you have any additional suggestions.

Thanks,
Vimal Mudalagi

**Comment by kartikeyasaran** [comment]
Hi Vimal,
That's a great idea! A web-based version would definitely enhance the game. I'm excited to see what you come up with.
Feel free to reach out if you need any help or have questions.
Best,
Kartikeya

**Comment by Vimal-Mudalagi** [comment]
Thanks!  I’ll get started & reach out if I need any help.

**Comment by Vimal-Mudalagi** [comment]
Hi Kartikeya,
I've submitted a pull request.
Please let me know if you have any feedback.
Thank you.
